In [1]:
import pandas as pd
import numpy as np

In [26]:
users = pd.read_csv('./accounts_context_0624.csv',encoding='utf-8')

In [2]:
clicks = pd.read_csv('./clicks_day_time_weekday_0624.csv',encoding='utf-8')

In [3]:
books = pd.read_csv('./product_dums_with_publish&price.csv',encoding='utf-8')

In [4]:
clicks_temp = clicks[['account_id','product_id']]

In [5]:
clicks_1 = clicks_temp.iloc[:20088683]
clicks_2 = clicks_temp.iloc[20088683:40177057]
clicks_3 = clicks_temp.iloc[40177057:]

In [6]:
books_temp = books.iloc[:,[2,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]]

In [10]:
pre_1 = clicks_1.merge(books_temp,how='left')
grouped_1 = pre_1.groupby('account_id')
pre_cat_1 = grouped_1.sum().iloc[:,1:]

In [15]:
pre_cat_1.to_csv('./pre_cat_1.csv')

In [7]:
pre_2 = clicks_2.merge(books_temp,how='left')
grouped_2 = pre_2.groupby('account_id')
pre_cat_2 = grouped_2.sum().iloc[:,1:]

In [8]:
pre_cat_2.to_csv('./pre_cat_2.csv')

In [7]:
pre_3 = clicks_3.merge(books_temp,how='left')
grouped_3 = pre_3.groupby('account_id')
pre_cat_3 = grouped_3.sum().iloc[:,1:]

In [8]:
pre_cat_3.to_csv('./pre_cat_3.csv')

In [9]:
pre_cat_1 = pd.read_csv('./pre_cat_1.csv',encoding='utf-8')

In [11]:
pre_cat_2 = pd.read_csv('./pre_cat_2.csv',encoding='utf-8')

In [ ]:
pre_cat_3 = pd.read_csv('./pre_cat_3.csv',encoding='utf-8')

In [18]:
pre_cat_total = pd.concat([pre_cat_1,pre_cat_2,pre_cat_3])

In [5]:
pre_cat_total['max_cat'] = pre_cat_total.iloc[:,1:].max(axis=1)

In [19]:
pre_cat_total['max_cat_name'] = pre_cat_total.iloc[:,1:26].idxmax(axis=1)

In [22]:
pre_cat_total

,account_id,cat__1.0,cat__2.0,cat__3.0,cat__4.0,cat__5.0,cat__7.0,cat__8.0,cat__9.0,cat__10.0,...,cat__20.0,cat__22.0,cat__23.0,cat__25.0,cat__27.0,cat__29.0,cat__33.0,cat__34.0,max_cat,max_cat_name
0,100001,0.0,1.0,233.0,5.0,2.0,0.0,4.0,8.0,7.0,...,5.0,13.0,18.0,0.0,4.0,0.0,18.0,44.0,233.0,cat__3.0
1,100004,1.0,0.0,17.0,0.0,1.0,0.0,2.0,0.0,0.0,...,0.0,1.0,0.0,1.0,3.0,0.0,7.0,2.0,17.0,cat__3.0
2,100014,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,14.0,1.0,1.0,14.0,cat__29.0
3,100018,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,cat__2.0
4,100020,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,2.0,2.0,7.0,cat__19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594107,16960408,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,cat__13.0
1594108,16960413,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,cat__34.0
1594109,16960422,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,cat__1.0
1594110,16960424,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,cat__10.0
1594111,16960430,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,cat__3.0

In [23]:
pre_cat_total.sort_values(by='max_cat')

,account_id,cat__1.0,cat__2.0,cat__3.0,cat__4.0,cat__5.0,cat__7.0,cat__8.0,cat__9.0,cat__10.0,...,cat__20.0,cat__22.0,cat__23.0,cat__25.0,cat__27.0,cat__29.0,cat__33.0,cat__34.0,max_cat,max_cat_name
1569239,16829000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,cat__1.0
549452,4871926,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,cat__1.0
1584223,16905256,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,cat__1.0
1347357,14654854,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,cat__1.0
33776,327491,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,cat__1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1379326,15149303,12.0,1.0,584.0,0.0,0.0,0.0,3831.0,3.0,0.0,...,1.0,2.0,0.0,0.0,16.0,12.0,198.0,4.0,3831.0,cat__8.0
693795,6237562,1.0,0.0,17.0,0.0,18.0,0.0,11.0,5.0,0.0,...,3.0,8.0,1.0,0.0,55.0,29.0,3956.0,43.0,3956.0,cat__33.0
1128327,11442039,0.0,1.0,2.0,0.0,549.0,12.0,2.0,10.0,3.0,...,3.0,4.0,7.0,45.0,4157.0,119.0,17.0,9.0,4157.0,cat__27.0
471329,4148490,133.0,0.0,2.0,2.0,52.0,1.0,0.0,102.0,0.0,...,4.0,4186.0,11.0,6.0,4.0,0.0,21.0,132.0,4186.0,cat__22.0
1331645,14364947,20.0,276.0,217.0,192.0,0.0,6.0,8.0,232.0,1.0,...,4564.0,64.0,30.0,0.0,19.0,0.0,93.0,65.0,4564.0,cat__20.0

In [24]:
pre_cat_total.to_csv('./user_cat_preferences_0624.csv')

In [27]:
new_users = users.merge(pre_cat_total,how='left')

In [30]:
new_users.to_csv('./accounts_context_add_prefer_0624.csv')